### ISSUE TITLE
Python exception source location not available in C++

### ISSUE THREAD

**Issue by torokati44** [wlav/cppyy#106]
The `PyException` class contains no information about the source location (`file:line`) of the represented Python exception.
It at least leaves the exception in the interpreter, so I can query it from Python later, but for some applications, having this in the C++ exception is essential.

See this snippet for demonstration (or possibly as a starting point for a future regression test):
```python3
import cppyy

cppyy.cppdef("""
#include <iostream>
#include <stdexcept>

class Foo {
    public:
        virtual void call() = 0;
        virtual ~Foo() {}
};

void call_foo(Foo* foo) {
    try {
        foo->call();
    } catch (std::exception& e) {
        std::cout << "Exception caught in C++:\\n----\\n" << e.what() << "\\n----\\n";
    }
}
""")

class Bar(cppyy.gbl.Foo):
    def call(self):
        raise RuntimeError("Ouch!")

bar = Bar()
try:
    cppyy.gbl.call_foo(bar)
except:
    print("Exception caught in Python:")
    print("----")
    import traceback
    traceback.print_exc()
    print("----")
```

**Comment by wlav** [comment]
Released with cppyy 2.4.2 and its dependencies. Again, thanks for the pull request.
