### ISSUE TITLE
Issue with newlines in CPP

### ISSUE THREAD

**Issue by Fancyapplebee** [wlav/cppyy#118]
In version 2.4.1 of cppyy, newlines require two backslashes instead of one.
For example.
This won't work:

cppyy.cppdef(
'''
struct something
{
    void baseLineStats()
    {
        std::cout << "as\n" ;
    }
};
''')

But this will work: 

cppyy.cppdef(
'''
struct something
{
    void baseLineStats()
    {
        std::cout << "as\\n" ;
    }
};
''')

**Comment by wlav** [comment]
Hasn't this always been the case? I.e., it's not new in 2.4.1? I also think it's the expected behavior. Anyway, Python has raw strings for this purpose: just prepend an `r`.
