### ISSUE TITLE
Different results when checking value in c++ vs. python

### ISSUE THREAD

**Issue by DeeeeLAN** [wlav/cppyy#12]
Hi, I am working with a C++ library called [slang](https://github.com/MikePopoloski/slang). I have a simple example here that is causing me some trouble:
```python
import cppyy

############################################################################
# Set up cppyy (runs from root directory)
############################################################################
# cppyy.ll.set_signals_as_exception(True)

cppyy.add_include_path('include')
cppyy.add_include_path('external')
cppyy.add_include_path('build/source')

cppyy.include('slang/syntax/SyntaxTree.h')

cppyy.load_library('build/lib/libslangcore')
cppyy.load_library('build/lib/libslangparser')
cppyy.load_library('build/lib/libslangruntime')
cppyy.load_library('build/lib/libslangcompiler')
############################################################################

slang = cppyy.gbl.slang
t1 = slang.SyntaxTree.fromText('always_ff')
t2 = slang.SyntaxTree.fromText(' always_ff')
kind1 = t1.root().childToken(1).kind
kind2 = t2.root().childToken(1).kind

cppyy.cppdef('''
namespace slang {
#include "slang/syntax/SyntaxTree.h"

auto t1 = SyntaxTree::fromText("always_ff");
auto t2 = SyntaxTree::fromText(" always_ff");
auto kind1 = t1->root().childToken(1).kind;
auto kind2 = t2->root().childToken(1).kind;
}
''')

print('python kind1: %d, kind2: %d' % (kind1, kind2))
print('c++    kind1: %d, kind2: %d' % (slang.kind1, slang.kind2))
print('combo  kind1: %d, kind2: %d' % (slang.t1.root().childToken(1).kind, slang.t2.root().childToken(1).kind))

# Results:
# python kind1:     98,  kind2: 131170
# c++    kind1: 6422626, kind2:     98
# combo  kind1:     98,  kind2: 131170
```

All 4 of the `kind` values should be 98. Essentially, `kind` is an enum value based on the text passed through a lexer. When additional characters are attached (a space, for example), they are saved in a separate list attached to the token. So in either case, `always_ff` should be getting passed to the lexer and the kind should be getting set to 98. The high values shown (`131170`, `6422626`) are not valid enum values, so I am not sure where they came from. I am sure this is not a simple task to debug, so let me know what additional information I can provide. My first thought is maybe somehow the value is getting replaced with a pointer to the value instead, although I am not sure if that makes sense. My C++ knowledge is not massive.

**Comment by wlav** [comment]
Do you have a simple reproducer, one that does not require installing slang?

Either way, it looks like the type of the enum doesn't match. (There are bunch of fixes for this already in the repo that will come out next release.) Point being that `131170` is `0x20062` in hex and `6422626` is `0x620062`. Iow., in both cases the high bits are incorrect (`98` being `0x62`), meaning that the underlying enum type is probably only 2 bytes instead of 4 (the default if the type doesn't resolve properly).

**Comment by DeeeeLAN** [comment]
Unfortunately I don't have an example. I didn't write the library so I am not confident I could extract a reliable test case. 

That being said, I think you hit the nail on the head, the enum type is a `uint16_t`. Should I try running again with the most recent changes pulled? Or is there another way to fix this issue?

**Comment by wlav** [comment]
It'll require a full rebuild, incl. the rather large `cppyy-cling`.  Not impossible, certainly, but annoying as it takes quite some wall-clock time: https://cppyy.readthedocs.io/en/latest/installation.html#install-from-source

I need to cut a new release (last one was more than 2 months ago), but am rather swamped for time for another couple of weeks at the least.

**Comment by DeeeeLAN** [comment]
Okay. Do you expect the changes will fix this issue? I am happy to build if it might work.

**Comment by wlav** [comment]
Check `kind2.__underlying`. If that is `'internal_enum_type_t'` (meaning unknown/unresolved), then there's a good chance that that is fixed. If it actually says `'int'` or `'unsigned int'`, then it's a different bug entirely.

**Comment by DeeeeLAN** [comment]
`slang.TokenKind.__underlying`, which is the type of kind, returns `internal_enum_type_t`.

**Comment by DeeeeLAN** [comment]
I have confirmed the recent updates to cppyy have fixed this issue, thanks.
