### ISSUE TITLE
2d char array only returns the first element

### ISSUE THREAD

**Issue by xuyumeng** [wlav/cppyy#120]
Hi, I was trying to access a c++ variable defined as 

```c
char str_array[3][8] = {"A1", "B1", "C1"};
```

but the cppyy only returns the first element `A1`

The problem can be reproduced by the following 
```python
cppyy.cppdef('char str_array[3][8] = {"A1", "B1", "C1"};')
type(cppyy.gbl.str_array)
# returns: str
cppyy.gbl.str_array
# returns: 'A1'
```

How can I access the whole array?

**Comment by wlav** [comment]
What version of cppyy is this? Current release shows `type(cppyy.gbl.str_array)` to be a `<class 'cppyy.LowLevelView'>` not `str`?

**Comment by xuyumeng** [comment]
I'm using `pyROOT`. The `cppyy` by default is `1.6.2`. I will ask the developer of `pyROOT` if it is possible to upgrade cppyy.

Thanks!

**Comment by wlav** [comment]
Yes, the ROOT folks use an ancient fork of cppyy and that's out of my hands. Good luck!
