### ISSUE TITLE
WinError 1114

### ISSUE THREAD

**Issue by HasbersHz** [wlav/cppyy#131]
``` python
import cppyy

lib = cppyy.load_library("life64.dll")

print(lib)
```

https://log.jocat.ru/bawoyacibo.php
Error output. (Too big)

'C:\Users\HasbersHz\AppData\Roaming\Python\Python310\site-packages\cppyy_backend\lib\libcppyy_backend.cp310-win_amd64.pyd'
This file doesn't exist.

I have a file libcppyy_backend.dll with dependencies.
![изображение](https://user-images.githubusercontent.com/98599824/220668578-886bcee3-8a73-468a-9946-b5e1b9cdc512.png)
I don't understand anything, but it doesn't seem like it's working

**Comment by wlav** [comment]
MSVC 2019 (IIRC, that's the newest version older than 2022).

The LLVM version needed is builtin, so can't be changed (b/c Cling made changes for interactivity; most of what Cling needs is being upstreamed into clang-repl, and will thus be part of the official LLVM releases, but we're not there yet).

**Comment by HasbersHz** [comment]
> MSVC 2019 (IIRC, that's the newest version older than 2022).
> 
> The LLVM version needed is builtin, so can't be changed (b/c Cling made changes for interactivity; most of what Cling needs is being upstreamed into clang-repl, and will thus be part of the official LLVM releases, but we're not there yet).

https://log.jocat.ru/pamabodoco.sql

**Comment by HasbersHz** [comment]
> MSVC 2019 (IIRC, that's the newest version older than 2022).
> 
> The LLVM version needed is builtin, so can't be changed (b/c Cling made changes for interactivity; most of what Cling needs is being upstreamed into clang-repl, and will thus be part of the official LLVM releases, but we're not there yet).

I just don't have much time to work on my project, so I just want to know what versions of the libraries and applications I need to put it to work.

**Comment by wlav** [comment]
As said, MSVC 2019. Hopefully, I can get cppyy 3.0.0 out in a week or so. Ironically, it's fully tested on Linux and Mac, still have to do Windows.

**Comment by HasbersHz** [comment]
> As said, MSVC 2019. Hopefully, I can get cppyy 3.0.0 out in a week or so. Ironically, it's fully tested on Linux and Mac, still have to do Windows.

All right, I'll use your project in the future, find no projects other than your that can load c++ dll. But I'm not lucky to have a project ready in two days, sleepless nights again, and use other, stupid method

**Comment by Developer-Mike** [comment]
What is the current status of the release of version 3.0.0?
