### ISSUE TITLE
add command to install virtualenv package before cppyy installation

### ISSUE THREAD

**Issue by amr-atif** [wlav/cppyy#133]
the docs for installation of cppyy don't contain enough steps to install virtualenv.

![image](https://user-images.githubusercontent.com/62966382/221372424-d3cc47db-57f4-4854-a190-c866b08b3f4f.png)

So I recommend adding a command to install virtualenv package to be able to create a virtual environment in order to install cppyy inside it and mention that in the description before the code.

$ python -m pip install virtualenv

**Comment by wlav** [comment]
Or rather, it should probably be `python -m venv` as of Python3.3 (as the text also says a bit higher up).
