### ISSUE TITLE
src/CPyCppyy.h:35:10: fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by NiKeYiGuN** [wlav/cppyy#136]
Building wheels for collected packages: CPyCppyy
  Building wheel for CPyCppyy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for CPyCppyy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /tmp/pip-build-env-s87zyjr5/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_ext
      building 'libcppyy' extension
      creating build
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/src
      /usr/bin/clang -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Iinclude -I/home/zhenhao/文档/GIT/mymeep/venv/include -I/usr/include/python3.9  src/API.cxx -o build/temp.linux-x86_64-cpython-39/src/API.o -O2 -pthread -std=c++1z -m64 -Wno-bad-function-cast -Wno-register -Wno-strict-aliasing
      In file included from src/API.cxx:2:
      src/CPyCppyy.h:35:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for CPyCppyy
Failed to build CPyCppyy
ERROR: Could not build wheels for CPyCppyy, which is required to install pyproject.toml-based projects

**Comment by NiKeYiGuN** [comment]
ubuntu18.04 python3.9

**Comment by wlav** [comment]
`apt install python3-dev`

**Comment by NiKeYiGuN** [comment]
> 

3q apt install python3.9-dev working.
