### ISSUE TITLE
Building from source produces an error when importing: "Error: Problems loading PCH"

### ISSUE THREAD

**Issue by DillanCMills** [wlav/cppyy#14]
I followed the instructions in https://cppyy.readthedocs.io/en/latest/repositories.html#building-from-source without any issues, everything built fine. When attempting to import, I get the following:
```
> python
Python 3.8.5 (default, Jul 26 2020, 02:44:08) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
error: Problems loading PCH: './env/lib/python3.8/site-packages/cppyy/allDict.cxx.pch.6.25.1'.
```
There is no other output. If I attempt to use the package, it crashes with a stacktrace. I assume there must be some incompatibility with my build environment. I am running on Debian 10. I have clang++-11 installed but I am not sure if it is getting picked up or not.

**Comment by wlav** [comment]
The clang version used is builtin and shouldn't be an issue.

I'd wipe `./env/lib/python3.8/site-packages/cppyy/allDict.cxx.pch.6.25.1`. It will rebuild on first use.

My best *guess* is a difference in build and work environment leading to the code finding different standard headers and somehow a mismatch with the precompiled ones.

**Comment by DillanCMills** [comment]
That makes sense. Since I originally had it installed through pip then installed the source build over the top, it looks like it still had the old allDict in place. Removing it triggered a rebuild and it looks good to go now, thanks.
