### ISSUE TITLE
Process finished with exit code 129 (interrupted by signal 1: SIGHUP)

### ISSUE THREAD

**Issue by NiKeYiGuN** [wlav/cppyy#142]
![image](https://user-images.githubusercontent.com/20457164/224003520-4d197f49-b83f-49fe-9554-f792af8b3783.png)

Ubuntu18.04
python3.9

I am very confused about this error, please give me some hints about this error and which way I should think about it。
Thanks.

**Comment by wlav** [comment]
The problem originates from ffi_closure_unix64_inner(), so line `#7`. The rest of the stack trace is simply the signal handler that generates the stack trace itself (i.e. "just the messenger").

I'm not familiar with that function; I presume it's some library function and that there's something more from `#10` and up that eventually traces back to your code.

**Comment by NiKeYiGuN** [comment]
OK,Thanks.
