### ISSUE TITLE
Possible memory issue with string_view

### ISSUE THREAD

**Issue by DillanCMills** [wlav/cppyy#18]
Hi again,

I have been making good progress with cppyy. I have run into the following situation though:
```python
text = cppyy.gbl.string_view('''
The standard Lorem Ipsum passage, used since the 1500s

"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC

"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
1914 translation by H. Rackham

"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC

"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
1914 translation by H. Rackham

"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains."
''')

print(text)
```

When I attempt to load a fairly large amount of text into a string_view (think a source code file), weird stuff happens. I can load it in just fine, and if I call `text.size()`, it gives me the correct number, but attempting to access the data either through printing it or using it in a different function on the C++ side fail. Sometimes it gives an error about failing to decode utf-8 characters. Sometimes it just prints out an empty string (or a handful of invisible characters, hard to tell). 

When I was playing around with it, if I started with a smaller amount of text and kept increasing the amount and printing the new variable each time, I could occasionally get one created that properly printed the entire string. That is what makes me think there is something weird going on with the memory storage. The exact length where it fails varies, but it is usually around 3000 characters.

I have not attempted to use a different string type, the compiler library uses string_view internally so I doubt it would make a difference. But maybe having a stable C string which gets converted to a string_view might work as a workaround. I would need to test it.

**Comment by wlav** [comment]
A `std::string_view` is a view on a character-based string. A Python string is of `unicode` type. What happens is that the string as given as an argument is converted to a temporary character string, then that `string_view` becomes a view on that temporary. In principle, that memory is managed by the original `unicode` string, but that, as used here, is itself a temporary.

A pythonization can fix this use case (as is done for `const char*` for example), however this code is also incorrect in C++ (as it would be for `const char*`, to be sure), where taking a character view of a unicode temporary won't end well either.

I'll figure out such a pythonization (I'm not sure why the converted character string is not kept alive by the `str` object, as I thought it would; probably a size limitation), but as a workaround, declare the text as character based (`bytes`) and tie its lifetime to the string_view:

```
a = b''' ... '''
text = cppyy.gbl.std.string_view(a)
text._buffer = a
```

**Comment by DillanCMills** [comment]
Thanks, that looks like it is working fine. I will use that for now.

**Comment by wlav** [comment]
Fixed in repo.

**Comment by wlav** [comment]
Fix released with 2.3.0 and its dependencies.

**Comment by DeeeeLAN** [comment]
So with your fix will I be able to assign to string_view directly now?

**Comment by wlav** [comment]
Yes, with the caveat that for it to work, the code internally needs to encode the unicode `str` to become a C++ string (`const char*`) that `string_view` can view. The assumption is made that the receiving end wants UTF-8 encoding (the default for Python). This is perfectly fine for strings that are otherwise expressible in ASCII (i.e. all characters used fit in single-byte, such as in the example above).

If the string contains any unicode code points not part of ASCII, it may not be what you want to receive C++ side and you'd have to encode the Python string with the desired encoding first. Any `bytes` object so passed in will get a life line to keep it alive for the duration of the `string_view`'s life time (thus also no memory problems), with no further conversion.
