### ISSUE TITLE
gcc error when trying to install cppyy-backend using pip

### ISSUE THREAD

**Issue by tpxHorus** [wlav/cppyy#181]
I am trying to install cppyy on arch for pypy3, and this error suddenly pops out. 
I have latest gcc installed. I tried changing STDCXX system variable and compiling with g++/clang/clang++ but this only changes the content of the information.
When using CPython pip or installing from AUR the same thing happens. 
Clearing pip cache does nothing.
I tried building from source but the same info comes up.

Output:
collecting cppyy-backend
  Using cached cppyy-backend-1.14.11.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cppyy-cling==6.28.0 in /home/notuser/.local/lib/pypy3.10/site-packages (from cppyy-backend) (6.28.0)
Building wheels for collected packages: cppyy-backend
  Building wheel for cppyy-backend (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cppyy-backend (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      running build
      running build_ext
      checking for build/temp.linux-x86_64-pypy310
      creating build/temp.linux-x86_64-pypy310
      creating build/temp.linux-x86_64-pypy310/src
      gcc -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-build-env-u9mqaiq4/overlay/lib/pypy3.10/site-packages/cppyy_backend/include -I/opt/pypy3/include/pypy3.10 -c src/clingwrapper.cxx -o build/temp.linux-x86_64-pypy310/src/clingwrapper.o -O2 -pthread -std=c++1z -m64
      In file included from /tmp/pip-build-env-u9mqaiq4/overlay/lib/pypy3.10/site-packages/cppyy_backend/include/Rtypes.h:30,
                       from src/callcontext.h:11,
                       from src/clingwrapper.cxx:11:
      /usr/include/string.h:506:15: error: declaration of ‘size_t strlcpy(char*, const char*, size_t) noexcept’ has a different exception specifier
        506 | extern size_t strlcpy (char *__restrict __dest,
            |               ^~~~~~~
      In file included from /tmp/pip-build-env-u9mqaiq4/overlay/lib/pypy3.10/site-packages/cppyy_backend/include/Rtypes.h:26:
      /tmp/pip-build-env-u9mqaiq4/overlay/lib/pypy3.10/site-packages/cppyy_backend/include/strlcpy.h:26:8: note: from previous declaration ‘size_t strlcpy(char*, const char*, size_t)’
         26 | size_t strlcpy(char *dst, const char *src, size_t siz);
            |        ^~~~~~~
      /usr/include/string.h:512:15: error: declaration of ‘size_t strlcat(char*, const char*, size_t) noexcept’ has a different exception specifier
        512 | extern size_t strlcat (char *__restrict __dest,
            |               ^~~~~~~
      /tmp/pip-build-env-u9mqaiq4/overlay/lib/pypy3.10/site-packages/cppyy_backend/include/strlcpy.h:27:8: note: from previous declaration ‘size_t strlcat(char*, const char*, size_t)’
         27 | size_t strlcat(char *dst, const char *src, size_t siz);
            |        ^~~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cppyy-backend
Failed to build cppyy-backend
ERROR: Could not build wheels for cppyy-backend, which is required to install pyproject.toml-based projects

**Comment by wlav** [comment]
Cling has a few C headers locally for compatibility reasons. I presume it has gotten out of date as you say you have the latest gcc. I see that upstream has added a gcc version check to `define STRLCPY`, which I don't have yet in cppyy-backend, so I need to pull that over.

Can you install by defining STRLCPY explicitly?
```
$ CFLAGS=-DSTRLCPY python -m pip install cppyy
```

**Comment by wlav** [comment]
Updated repo, which should fix it next release.

**Comment by wlav** [comment]
Released with 3.1.0. Feel free to reopen if you continue having issues.
