### ISSUE TITLE
Support for Python3.11?

### ISSUE THREAD

**Issue by dizhouwu** [wlav/cppyy#200]
Hi,

Thanks for the very interesting work here. Any chance a version will be released which supports Python3.11 soon? 

Thank you so much!

**Comment by wlav** [comment]
py11 fixes have been in the repo for some time. I working out a bunch of portability issues that 3.0.0 has (just finished gcc12 issues today), so hopefully can cut a release again soon.

**Comment by dizhouwu** [comment]
> py11 fixes have been in the repo for some time. I working out a bunch of portability issues that 3.0.0 has (just finished gcc12 issues today), so hopefully can cut a release again soon.

Thank you so much!

**Comment by torokati44** [comment]
Is that new release also going to bring Python 3.12 compatibility? 👀

**Comment by wlav** [comment]
Added a few days ago. There are a couple of things I don't quite understand the implications of purely from the Python docs, but all tests run.

**Comment by torokati44** [comment]
Great, thank you!

**Comment by wlav** [comment]
Should all be good now with release 3.1.0. Feel free to reopen if you find otherwise.
