### ISSUE TITLE
Namespace confusion in type lookup

### ISSUE THREAD

**Issue by saraedum** [wlav/cppyy#253]
Consider the following code snippet:

```py
import cppyy

cppyy.cppdef(r"""
namespace X {
    class C {};
}

namespace Y {
    namespace Z {
        template <typename T> void f() {}
    }

    namespace X {
        class D {};
    }
}
""")

cppyy.gbl.Y.Z.f[type(cppyy.gbl.X.C)]()
```

I would expect this to work (and do nothing) but instead I get:

```
TypeError: Could not find "f<X::C>" (set cppyy.set_debug() for C++ errors):
  Failed to instantiate "f<X::C>()"
```

With `cppyy.set_debug()`, I get:

```
lookup.funcname.file:1:6: error: no member named 'C' in namespace 'Y::X'
f<X::C>
```

So the type is translated incorrectly here. It should be `::X::C` I guess.

---

This happened with the latest cppyy (3.1.2) from conda-forge on Linux and also with the cppyy from pip on Linux.

**Comment by wlav** [comment]
Fix released with cppyy 3.5.0 and its dependencies.
