### ISSUE TITLE
C++ maximum version 

### ISSUE THREAD

**Issue by oliverlee** [wlav/cppyy#257]
If I understand issue #137 correctly, the maximum version of cppyy is determined by cling and I won't be able to use this library for a C++ project that requires C++23.

If that's the case, would you mind clarifying the requirements in the README? If not, then I must have missed this case in the existing documentation.

**Comment by wlav** [comment]
Yes, this is correct. Currently, the backend is based on LLVM13. LLVM16 is in the works (upstream has this in production and is working on LLVM18, getting close).

Standards support is described in the [documentation](https://cppyy.readthedocs.io/en/latest/installation.html#c-standard-with-pip).

**Comment by oliverlee** [comment]
Thanks! I'm looking forward to trying this out in the future.

I suggest highlighting this:
> Note that the build will automatically lower your choice if the compiler used does not support a newer standard.

and editing the first sentence in the installation section to be:
> cppyy requires a (modern, but not too modern) C++ compiler.
