### ISSUE TITLE
manual installation segfaults

### ISSUE THREAD

**Issue by marc1uk** [wlav/cppyy#35]
Trying to install cppyy from sources on centos7 segfaults immediately on import. I've tried to follow the instructions as closely as possible, and have a hopefully reproducible version based on a singularity container here:

```
/// get the centos7 latest docker image
$ sudo singularity build centos7.sif docker://cern/cc7-base:latest

/// make an overlay for storing changes to the container
$ mkdir -p -m 777 overlay/upper overlay/work
$ dd if=/dev/zero of=overlay.img bs=1M count=3000 && mkfs.ext3 -d overlay overlay.img

/// start it up as root user and install dependencies
$ sudo singularity shell --overlay overlay.img --cleanenv --no-home centos7.sif

> # yum install gcc-c++ gcc make cmake git python36 python36-libs python36-devel python36-pip patch
> # python3 -m pip install --upgrade pip
> // N.B. without upgrading pip,  `--no-use-pep517` is not recognised.
> # python3 --version
> Python 3.6.8
> # python3 -m pip -V
> pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
> # g++ --version
> g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
> # cmake --version
> cmake version 2.8.12.2
> # mkdir /home/user
> # chown -R 1000 /home/user
> # exit

/// start it up again as non-root user
$ singularity shell --overlay overlay.img --cleanenv --no-home centos7.sif

/// cppyy installation:
> $ cd /home/user
> $ export STDCXX=11
> # N.B. without the above, building cppyy-cling returns: `gcc: error: unrecognized command line option '-std=c++1z'`
> $ export EXTRA_CLING_ARGS='-nocudainc'
> # N.B. without the above, importing cppyy returns CUDA libraries not found, and many compiler errors.
> $ export PATH=/home/user/.local/bin:$PATH
> # as recommended in the install guide
> $ export LD_LIBRARY_PATH=/home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib:$LD_LIBRARY_PATH
> # also noted in the install guide
> $ 
> $ git clone https://github.com/wlav/cppyy-backend.git
> $ cd cppyy-backend/cling
> $ python3 setup.py egg_info
> $ python3 create_src_directory.py
> $ python3 -m pip install . --upgrade
> $
> $ cd ../clingwrapper
> $ python3 -m pip install . --upgrade --no-use-pep517 --no-deps
> $ 
> $ cd ../../
> $ git clone https://github.com/wlav/CPyCppyy.git
> $ cd CPyCppyy
> $ python3 -m pip install . --upgrade --no-use-pep517 --no-deps
> $ 
> $ cd ../
> $ git clone https://github.com/wlav/cppyy.git
> $ cd cppyy
> $ python3 -m pip install . --upgrade --no-deps --verbose

/// no errors during installation at this point, but cppyy immediately segfaults on import:
> $ python3
> >>> import cppyy
/home/user/.local/lib/python3.6/site-packages/cppyy_backend/loader.py:134: UserWarning: No precompiled header available (local variable 'cling_args' referenced before assignment); this may impact performance.
  warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)
> Segmentation fault
```

Any suggestions? I'm building from source as centos7 contains g++4.8.5 (as shown) and the guide says that this should sufficient, but only for manual installation.
I would like to avoid conda etc as I've had a lot of issues integrating them with other installations and packaging systems in the past.

**Comment by marc1uk** [comment]
A bit more information comes out if I don't export the path to the `cppyy_backend/lib` directory to `LD_LIBRARY_PATH`, in which case I get the following behaviour:

```
$ singularity shell --overlay overlay.img --cleanenv --no-home centos7 
Singularity> export STDCXX=11
Singularity> export EXTRA_CLING_ARGS='-nocudainc'
Singularity> export PATH=/home/user/.local/bin:$PATH
Singularity> python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
/home/user/.local/lib/python3.6/site-packages/cppyy_backend/loader.py:134: UserWarning: No precompiled header available (local variable 'cling_args' referenced before assignment); this may impact performance.
  warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)
warning: argument unused during compilation: '-nocudainc'
>>> from cppyy.gbl.std import vector
>>> v = vector[int]()
input_line_17:2:19: error: no type named 'TStreamerInfo' in namespace 'CppyyLegacy'
 new CppyyLegacy::TStreamerInfo{};
     ~~~~~~~~~~~~~^
 *** Break *** segmentation violation
 Generating stack trace...
 0x00007ff217ed359e in CppyyLegacy::TClass::TClass(char const*, short, bool) + 0x2be from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib/libCoreLegacy.so
 0x00007ff213a43be1 in <unknown> from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib/libCling.so
 0x00007ff217ece6a5 in CppyyLegacy::TClass::GetClass(char const*, bool, bool) + 0x6f5 from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib/libCoreLegacy.so
 0x00007ff212f65705 in Cppyy::GetScope(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /home/marc/cppyy-backend/clingwrapper/src/clingwrapper.cxx:564 from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib/libcppyy_backend.so
 0x00007ff2126f0af4 in CPyCppyy::CreateScopeProxy(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _object*, unsigned int) at /home/user/CPyCppyy/src/ProxyWrappers.cxx:566 from /home/user/.local/lib/python3.6/site-packages/libcppyy.cpython-36m-x86_64-linux-gnu.so
 0x00007ff212731ab4 in <unknown> from /home/user/.local/lib/python3.6/site-packages/libcppyy.cpython-36m-x86_64-linux-gnu.so
 0x00007ff21a787a47 in PyCFunction_Call + 0x57 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7edf64 in _PyEval_EvalFrameDefault + 0x68f4 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f2317 in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f435f in _PyFunction_FastCallDict + 0x24f from /lib64/libpython3.6m.so.1.0
 0x00007ff21a749d9e in _PyObject_FastCallDict + 0x10e from /lib64/libpython3.6m.so.1.0
 0x00007ff21a749eb1 in _PyObject_Call_Prepend + 0x61 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a749b23 in PyObject_Call + 0x43 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a79cea9 in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7e8088 in _PyEval_EvalFrameDefault + 0xa18 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f35ed in PyEval_EvalCodeEx + 0x22d from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f410b in PyEval_EvalCode + 0x3b from /lib64/libpython3.6m.so.1.0
 0x00007ff21a87c53e in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a729246 in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7293e8 in PyRun_InteractiveLoopFlags + 0xe5 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7294a9 in PyRun_AnyFileExFlags + 0x39 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a882a7b in Py_Main + 0x69b from /lib64/libpython3.6m.so.1.0
 0x0000000000400ab9 in main + 0x119 from python3
 0x00007ff2199d0555 in __libc_start_main + 0xf5 from /lib64/libc.so.6
 0x0000000000400c40 in <unknown> from python3
 *** Break *** segmentation violation
 Generating stack trace...
 0x00007ff217ed359e in CppyyLegacy::TClass::TClass(char const*, short, bool) + 0x2be from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib/libCoreLegacy.so
 0x00007ff213a43be1 in <unknown> from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib/libCling.so
 0x00007ff217ece6a5 in CppyyLegacy::TClass::GetClass(char const*, bool, bool) + 0x6f5 from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib/libCoreLegacy.so
 0x00007ff212f65705 in Cppyy::GetScope(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /home/user/cppyy-backend/clingwrapper/src/clingwrapper.cxx:564 from /home/marc/.local/lib/python3.6/site-packages/cppyy_backend/lib/libcppyy_backend.so
 0x00007ff2126f0af4 in CPyCppyy::CreateScopeProxy(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _object*, unsigned int) at /home/marc/CPyCppyy/src/ProxyWrappers.cxx:566 from /home/user/.local/lib/python3.6/site-packages/libcppyy.cpython-36m-x86_64-linux-gnu.so
 0x00007ff212731ab4 in <unknown> from /home/user/.local/lib/python3.6/site-packages/libcppyy.cpython-36m-x86_64-linux-gnu.so
 0x00007ff21a787a47 in PyCFunction_Call + 0x57 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7edf64 in _PyEval_EvalFrameDefault + 0x68f4 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f2317 in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f435f in _PyFunction_FastCallDict + 0x24f from /lib64/libpython3.6m.so.1.0
 0x00007ff21a749d9e in _PyObject_FastCallDict + 0x10e from /lib64/libpython3.6m.so.1.0
 0x00007ff21a749eb1 in _PyObject_Call_Prepend + 0x61 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a749b23 in PyObject_Call + 0x43 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a79cea9 in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7e8088 in _PyEval_EvalFrameDefault + 0xa18 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f35ed in PyEval_EvalCodeEx + 0x22d from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7f410b in PyEval_EvalCode + 0x3b from /lib64/libpython3.6m.so.1.0
 0x00007ff21a87c53e in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a729246 in <unknown> from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7293e8 in PyRun_InteractiveLoopFlags + 0xe5 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a7294a9 in PyRun_AnyFileExFlags + 0x39 from /lib64/libpython3.6m.so.1.0
 0x00007ff21a882a7b in Py_Main + 0x69b from /lib64/libpython3.6m.so.1.0
 0x0000000000400ab9 in main + 0x119 from python3
 0x00007ff2199d0555 in __libc_start_main + 0xf5 from /lib64/libc.so.6
 0x0000000000400c40 in <unknown> from python3
```

it appears that the libraries in /home/user/.local/lib/python3.6/site-packages/cppyy_backend/lib` are found without any issue, and a stack-trace is generated this time.

**Comment by marc1uk** [comment]
Perhaps this latter one is the same as [this issue](https://bitbucket.org/wlav/cppyy/issues/324/using-cppyy-master-instead-of-root-s-cppyy), but I must admit I'm a bit lost on the workaround:

> I don’t see any other way than using the PCH and providing the include directory to Cling.

> Indeed, it worked by including the TStreamerInfo.h. 

Despite the warnings, I do have a PCH file: `/home/user/.local/lib/python3.6/site-packages/cppyy/allDict.cxx.pch.6.25.2` (removing it and having it rebuilt doesn't change anything).  I also have `TStreamerInfo.h` located in `/home/marc/.local/lib/python3.6/site-packages/cppyy_backend/include`.
What else needs to happen?

**Comment by wlav** [comment]
The segfault should not happen: running w/o PCH should be fine, so that's a separate issue. But the error indicated is a Python one: `local variable 'cling_args' referenced before assignment` in `cppyy_backend.loader`. This is indeed a problem in master, where `cling_args` is not set if a PCH name was defined.

Now fixed in repo: a pull should do the trick.

As for the name: the PCH will differ based on compiler flags. AVX, OpenMP, and CUDA being the biggies. I'm trying to work around that to keep separate PCHs for those different combinations of uses. Precompiled modules should solve this more elegantly, but upstream doesn't guarantee their use on Windows yet, and I haven't had the time to verify them on that platform. I was told separately (e-mail) that master has issues if CUDA is found, but it is too new (Cling as-is can handle up to 10.2.) That'll require a separate fix in case you run into it. (CUDA support is new in master and under active development; to be released with 2.3.0.)

Do you need master? If not, all releases are tagged and so using the latest release tag may make your life easier.

**Comment by marc1uk** [comment]
Thanks for the quick fix, I'm rebuilding now and will see if it fixes it. I don't (currently) need CUDA, so would also be happy to try a the latest release tag instead if this doesn't work out. 
In the meantime, perhaps this is already clear (I'm a bit lost if i'm honest), but i realised that after removing `/home/user/.local/lib/python3.6/site-packages/cppyy/allDict.cxx.pch.6.25.2` and re-importing cppyy, although it reported no errors and suggested it was rebuilding the header:
```
>>> import cppyy
(Re-)building pre-compiled headers (options:-nocudainc --cuda-host-only); this may take a minute ...
warning: argument unused during compilation: '-nocudainc'
warning: argument unused during compilation: '-nocudainc'
(Re-)building pre-compiled headers (options:-nocudainc --cuda-device-only); this may take a minute ...
error: -E or -x required when input is from standard input
error: invalid argument '-std=c++11' not allowed with 'C'
error: -E or -x required when input is from standard input
error: invalid argument '-std=c++11' not allowed with 'C'
Error: Parsing Linkdef file etc/dictpch/allLinkDefs.h
/home/marc/.local/lib/python3.6/site-packages/cppyy_backend/loader.py:134: UserWarning: No precompiled header available (failed to build); this may impact performance.
  warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)
warning: argument unused during compilation: '-nocudainc'
>>> 
```
it did not regenerate this file. Following the instructions for 'multiple PCH versions' gave a compilation error which suggested that although it picked up the `EXTRA_CLING_ARGS` variable, it didn't use it:
```
> $python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy_backend.loader as l
>>> l.set_cling_compile_options(True)
>>> install_path='/home/user/.local/lib/python3.6/site-packages/cppyy'
>>> l.ensure_precompiled_header(install_path)
(Re-)building pre-compiled headers (options:-nocudainc -x cuda -D__CUDA__ -O2 -mavx --cuda-host-only); this may take a minute ...
Error: libcudart.so not found!
Please add the cuda lib path to LD_LIBRARY_PATH or set it via -L argument.
cling: In file included from input_line_10:9:
In file included from ./etc/dictpch/allHeaders.h:4:
In file included from /home/user/.local/lib/python3.6/site-packages/cppyy_backend/etc//cling/lib/clang/9.0.1/include/__clang_cuda_runtime_wrapper.h:32:
/home/user/.local/lib/python3.6/site-packages/cppyy_backend/etc//cling/lib/clang/9.0.1/include/__clang_cuda_math_forward_declares.h:102:16: error: expected unqualified-id
__DEVICE__ int fpclassify(double);
```
Note: `(options:-nocudainc -x cuda -D__CUDA__ -O2 -mavx --cuda-host-only); ` shows it has seen `-nocudainc`, but it still seems to rebuild with CUDA.

**Comment by wlav** [comment]
Yes, I need to go over the various different options (CUDA, no CUDA, too new CUDA). Also, it should be that unless CUDA Is explicitly enabled, it shouldn't be used for now (there are many more setup problems; in particular each CUDA version requires _very_ specific versions of gcc to work properly; can't be helped: that's on NVidia). The envar to control CUDA is supposed to be `CLING_ENABLE_CUDA`, but reportedly doesn't work correctly yet either ...

The way that CUDA currently is supported, is by having two JITs at run-time: one for the device, one for the host. At the moment, both run for all code, which is another thing that should be made more flexible (choice of host, device, or both at the Python level), but that's secondary. Anyway, that's where you see those `--cuda-host-only` (first JIT) and `--cuda-device-only` (second JIT) parts coming from: everything is duplicated.

**Comment by marc1uk** [comment]
Unfortunately that didn't seem to do it - I rebuilt the container from scratch to ensure there wasn't anything carried over, using the same procedure as above, but get this:
```
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
(Re-)building pre-compiled headers (options:-nocudainc --cuda-device-only); this may take a minute ...
error: -E or -x required when input is from standard input
error: invalid argument '-std=c++11' not allowed with 'C'
error: -E or -x required when input is from standard input
error: invalid argument '-std=c++11' not allowed with 'C'
Error: Parsing Linkdef file etc/dictpch/allLinkDefs.h
/home/marc/.local/lib/python3.6/site-packages/cppyy_backend/loader.py:134: UserWarning: No precompiled header available (failed to build); this may impact performance.
  warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)
warning: argument unused during compilation: '-nocudainc'
```
with the same segmentation fault when I try to use a std::vector.

**Comment by marc1uk** [comment]
> The envar to control CUDA is supposed to be CLING_ENABLE_CUDA, but reportedly doesn't work correctly yet either ...

after doing `export CLING_ENABLE_CUDA=0`, I was actually able to follow the instructions for building specific cases PCH files by loading the `cppyy_backend.loader`, and this time it did seem to not attempt to use CUDA and didn't give the above compiler errors. Unfortunately the result is otherwise the same as my last post, with errors about `-E or -x required when input is from standard input` and `invalid argument '-std=c++11' is not allowed with 'C'`.

**Comment by marc1uk** [comment]
It seems as though release `cppyy-cling-6.25.2` more or less worked. The only difference in above was checking out tag cppyy-cling-6.25.2 before building. On the first attempt to import cppyy after installation, i got:
```
>>> import cppyy
error: Problems loading PCH: '/home/user/.local/lib/python3.6/site-packages/cppyy/allDict.cxx.pch.6.25.2'.
>>>
```
so I removed that file and regenerated it:
```
$ rm /home/user/.local/lib/python3.6/site-packages/cppyy/allDict.cxx.pch.6.25.2
$ python3
>>> import cppyy_backend.loader as l
>>> l.set_cling_compile_options(True)
>>> install_path='/home/marc/.local/lib/python3.6/site-packages/cppyy'
>>> l.ensure_precompiled_header(install_path)
(Re-)building pre-compiled headers (options: -O2 -mavx); this may take a minute ...
>>> 
```
and after that, everything I've tested so far seems to work.

**Comment by wlav** [comment]
Yes, I don't update the version numbers in dev until released as using pip for testing is too much trouble otherwise, so both the tagged release and master use the same named PCH, leading to the need to manually remove it. Note that I got tired of that, too, so in master one can set `CLING_REBUILD_PCH=1` to force rebuilding, rather than having to go and find the relevant PCH.

Master is now also fixed in regards CUDA enabling: CUDA properly disabled by default and if requested, version-checked; so should now work from source as expected.

I was not exactly (see below) able to create a segfault with any configuration, but the CUDA PCH was still being build even when `CLING_STANDARD_PCH=none`. That is now fixed.

I was not exactly able to reproduce `invalid argument '-std=c++11' is not allowed with 'C'`. My thinking here is that there's something going wrong with `EXTRA_CLING_ARGS` as set, although I don't see where. Point being that that error can be elicited by using `EXTRA_CLING_ARGS=-x c`, which may have com about as a mishap from what should have been `-x cuda`? If I do set `-x c`, however, I get a segfault (I think it's in upstream trying to retrieve a C++ context and not checking the result for `nullptr`, an occurrence too common to make it worth fixing unless someone comes up with a use case for wanting C only :) ).

**Comment by marc1uk** [comment]
I see, thanks for the info on `CLING_REBUID_PCH=1`, that'll help when writing writing this into the Dockerfile.
A bit curious that the `-x / -E` wasn't reproducible, but at least the singularity process above ought to reproducible if it pops up again. 

Thanks for all the help, and for the awesome c++/python interface. I shopped around for a long time looking at boost python / pyste / pybind11 / SWIG / autoWIG / robotpy / py++ / pycxx ... before eventually finding cppyy, and now wonder why anyone would use anything else!

**Comment by wlav** [comment]
> and now wonder why anyone would use anything else!

Two main reasons: 1) the dependency on Cling, hence LLVM, which is rather heavy; and 2) distribution difficulties: w/o distributing the PCH (which is big), a compiler and header files are required on the deployment site. The latter is particularly hard on Windows users (installing MSVC is nowhere near as easy as installing gcc or Xcode).

The second point could be removed as an issue with a bit of work as Cling itself is a compiler, so no other compiler is necessary, and a PCH can be used instead of locally installed C++ headers. This works with pyinstaller, for example, but a more generalized solution is possible and one day I'll get to it.

**Comment by marc1uk** [comment]
I see. Fortunately neither of those are particularly onerous in our use case, while the advantage of not having to write explicit wrappers around everything are huge.
