### ISSUE TITLE
cppyy fails to find template type with template _template_ type as final parameter

### ISSUE THREAD

**Issue by tristanpye** [wlav/cppyy#44]
Further to Issue #37, (now fixed, thanks!) I see further failures when the final parameter is a template template type (as opposed to a plain template type in #37). 

[cppyybug.txt](https://github.com/wlav/cppyy/files/8351888/cppyybug.txt)

Interestingly, the `VA` template in the reproducer above is intended to match the signature of `std::vector`, and indeed `std::vector` also fails on MacOS (clang 12), but not on CentOS g++ v10 devtoolset-10). Both Python 10.

On MacOS `std::vector` fails in the same way as `VA`, unless `f` is inside a namespace, when it fails on different tests... all very confusing.

Our real-world case is using `std::vector` and `std::function` on CentOS and failing, so some more digging needed to find what is causing that, as this test case does not fail for that combination!

**Comment by Fredbasset** [comment]
I said above that further digging was need to find what was causing our problem... it seems that the template parameter being in a namespace also causes failure. Enhanced reproducer attached.

[cppyybug.txt](https://github.com/wlav/cppyy/files/8352613/cppyybug.txt)

**Comment by wlav** [comment]
Thanks for the nice reproducer!

Fixed in repo. There's an unlikely branch where this happens. Fix is ugly, but upstream is working on a replacement of all this name massaging, so hopefully all this code will disappear eventually.
