### ISSUE TITLE
Failing to correctly infer return type as function pointer

### ISSUE THREAD

**Issue by cstyl** [wlav/cppyy#65]
Hi, I've been trying to port with cppyy an example that would return a function pointer as follows:

```py
import cppyy

cppyy.cppdef("""
typedef void (*func_t)(void);

func_t foo(){
    return func_t();
}
""")

cppyy.gbl.foo()
```

However, it fails to infer the return type with the following error:

```
input_line_19:11:15: error: expected expression
      ((FP5 (&)())foo)();
```

Thanks,
Chris

**Comment by wlav** [comment]
Yes, was ignored. Now in repo.
