### ISSUE TITLE
ROOT dependencies

### ISSUE THREAD

**Issue by dougschouten** [wlav/cppyy#77]
Not sure if this is the right repo issues dB to populate or if I should be submitting for cppyy-backend, but my problem is that if I try to `import cppyy` when I have ROOT libraries in my `LD_LIBRARY_PATH` then I get a segfault, presumably because of a mistmatch and name clash in the libraries in the `cppyy-backend` package I have installed in `site-packages' and the ROOT libraries.

Two questions:
- is my experience of this issue expected, or have I done something wrong (I've just compiled ROOT binaries, and used the usual `thisroot.sh` to configure my shell environment ... been doing this for many years now)
- is there any chance that a fully working Cling distribution can be extricated fully  from ROOT and maintained separately ... maybe not a question you can answer (/rant also the "TBlah" syntax continues to irk me, and the fact that ROOT is a single monolithic package with GSL reimplementation and a C language interpreter bundled up with histogram visualization and Geant geometry handlers / rant).

**Comment by wlav** [comment]
`cppyy-backend` does not pull in the ROOT libraries: there's some ROOT stuff left over (work is being done to remove this), but the libraries have all been renamed (and everything ROOT was hidden in a namespace). More likely, if you sourced `thisroot.sh` and ROOT shipped with Python bindings enabled, it comes with its own version of `cppyy`, so now you have two, and it's the ROOT one that is pulling in stuff it shouldn't. That's on the ROOT team for copying the cppyy repos and incorporating them into ROOT (and then not keeping them up-to-date and compatible).

Anyway, you can quickly check:

```
$ python
>>> import cppyy
>>> print(cppyy)
```

to see which is being imported.

As for Cling, yes, Cling proper is its own product: https://rawgit.com/root-project/cling/master/www/index.html

**Comment by wlav** [comment]
Closing as presumed clarified. Feel free to reopen or open another issue if there are further questions.
